name: Sync main documentation

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: quarkusio/quarkus
          path: .quarkus-main-repository

      - name: Set up JDK 11
        # Uses sha for added security since tags can be updated
        uses: joschi/setup-jdk@e87a7cec853d2dd7066adf837fe12bf0f3d45e52
        with:
          java-version: 11
      - name: Build generated documentation
        working-directory: .quarkus-main-repository
        run: ./mvnw -DskipTests -DskipITs -DskipExtensionValidation -Dskip.gradle.tests clean install

      - name: Sync guides
        run: |
          rsync -vr --delete \
            --exclude='**/*.html' \
            --exclude='**/index.adoc' \
            --exclude='**/attributes.adoc' \
            --exclude='**/guides.md' \
            .quarkus-main-repository/docs/src/main/asciidoc/* \
            _versions/main/guides/
      - name: Sync generated documentation
        run: |
          rsync -vr --delete \
            .quarkus-main-repository/target/asciidoc/generated/ \
            _generated-config/main
      - name: Commit changes
        run: git commit -am "Sync documentation of main branch"

      - name: Push changes to ${{github.base_ref}}
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_API_TOKEN }}
          branch: ${{github.base_ref}}
